import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  Ban,
  Bell,
  CheckSquare,
  Clock,
  CreditCard,
  FileSignature,
  FileText,
  FlaskConical,
  FolderKanban,
  Gauge,
  Inbox,
  LayoutDashboard,
  MessageSquare,
  Paperclip,
  Quote,
  Receipt,
  RotateCcw,
  Rocket,
  Settings,
  TrendingUp,
  UserCog,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";
import type { AdminIconName } from "@/data/adminNav";

export const adminIcons: Record<AdminIconName, LucideIcon> = {
  overview: LayoutDashboard,
  leads: Inbox,
  clients: Users,
  projects: FolderKanban,
  tasks: CheckSquare,
  files: Paperclip,
  proposals: FileText,
  contracts: FileSignature,
  invoices: Receipt,
  payments: CreditCard,
  messages: MessageSquare,
  notifications: Bell,
  team: UserCog,
  capacity: Gauge,
  payroll: Wallet,
  time: Clock,
  activity: Activity,
  settings: Settings,
  profile: UserRound,
  qa: FlaskConical,
  needsChanges: RotateCcw,
  blocked: Ban,
  deployments: Rocket,
  overdue: AlertTriangle,
  reports: TrendingUp,
  testimonials: Quote,
};
